obj-y += div64.o memzero.o memset.o memcpy.o memchr.o strchr.o lib1funcs.o clearbit.o testchangebit.o testclearbit.o testsetbit.o setbit.o findbit.o getuser.o putuser.o muldi3.o uaccess.o ashldi3.o ashrdi3.o memmove.o delay.o

