#!/usr/bin/env python
#  -*- mode: python; -*-
import sys

# add fallback path for non-native python path installs if needed
sys.path.append('/usr/lib/python')
sys.path.append('/usr/lib/python2.4')
from xen.xm import main

main.main(sys.argv)
